TARGET_SPECIFIC_HEADER_PATH := device/alcatel/cocktail/include

USE_CAMERA_STUB := false
BOARD_USES_GENERIC_AUDIO := true

# Board & CPU
TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
# TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_ARCH := arm
TARGET_CPU_ABI  := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_USE_SCORPION_BIONIC_OPTIMIZATION := true
TARGET_USE_SCORPION_PLD_SET := true
TARGET_SCORPION_BIONIC_PLDOFFS := 6
TARGET_SCORPION_BIONIC_PLDSIZE := 128

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

#flag
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DQCOM_FM_ENABLED
COMMON_GLOBAL_CFLAGS += -DBINDER_COMPAT -DICS_CAMERA_BLOB -DQCOM_NO_SECURE_PLAYBACK -DANCIENT_GL
COMMON_GLOBAL_CFLAGS += -DTARGET7x30 -DTARGET_MSM7x30 -DREFRESH_RATE=60 -DQCOM_ICS_DECODERS


# Kernel/bootimg
TARGET_KERNEL_SOURCE := kernel/alcatel/cocktail-kernel-msm7x30
TARGET_KERNEL_CONFIG := OT995_defconfig
BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=cocktail
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01300000
# BOARD_FORCE_RAMDISK_ADDRESS := 0x01300000
BOARD_FLASH_BLOCK_SIZE := 1

#
# Partition sizes
#
# XXX - this has an extra zero appended to be able to build recovery
# We can only fit the kernel if it's stripped down and LZMA-compressed..
BOARD_VOLD_MAX_PARTITIONS := 8
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 5242880
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 52428800
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 262144000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1064304640
BOARD_FLASH_BLOCK_SIZE := 4096

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_RECOVERY_NO_FLASH := true
TARGET_PREBUILT_RECOVERY_KERNEL := device/alcatel/cocktail/recovery/recovery-kernel
# TARGET_PREBUILT_KERNEL := device/alcatel/cocktail/kernel
TARGET_RECOVERY_INITRC := device/alcatel/cocktail/init.recovery.rc
TARGET_RELEASETOOL_OTA_FROM_TARGET_SCRIPT := device/alcatel/cocktail/releasetools/ota_from_target_files

# Misc
BOARD_EGL_CFG := device/alcatel/cocktail/egl.cfg
TARGET_USES_OVERLAY := false
TARGET_USES_GENLOCK := true
TARGET_USES_SF_BYPASS := false
TARGET_GRALLOC_USES_ASHMEM := true
TARGET_HAVE_BYPASS := false
TARGET_HAVE_TSLIB := true

# FM Radio
BOARD_HAVE_FM_RADIO := true
BOARD_FM_DEVICE := bcm4330
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

# camera
CAMERA_USES_SURFACEFLINGER_CLIENT_STUB := true
COMMON_GLOBAL_CFLAGS += -DNO_UPDATE_PREVIEW
BOARD_NEEDS_MEMORYHEAPPMEM := true
TARGET_DISABLE_ARM_PIE := true
BOARD_CAMERA_USE_MM_HEAP := true

# Avoid webkit rendering bug
TARGET_FORCE_CPU_UPLOAD := true
ENABLE_WEBGL := true
WEBCORE_INPAGE_VIDEO := true

# Boot animation speedup
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

# Graphics
# TARGET_HARDWARE_3D := false
BOARD_USES_ADRENO_200 := true
TARGET_QCOM_HDMI_OUT := true
TARGET_USES_C2D_COMPOSITION := false
TARGET_NO_HW_VSYNC := false
# BOARD_EGL_NEEDS_LEGACY_FB := true
USE_OPENGL_RENDERER := true
# TARGET_QCOM_AUDIO_VARIANT := legacy
TARGET_QCOM_DISPLAY_VARIANT := legacy


# Qualcomm stuff
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_GPS := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
BOARD_HAVE_QCOM_FM := true
BOARD_USES_QCNE := true

# radio interface
BOARD_MOBILEDATA_INTERFACE_NAME := "rmnet0"

BOARD_VENDOR_QCOM_AMSS_VERSION := 6225
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := cocktail
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000

# WiFi
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd
BOARD_WLAN_DEVICE           := bcmdhd
BOARD_WLAN_DEVICE_REV       := bcm4330_b2
WIFI_DRIVER_FW_PATH_PARAM   := "/sys/module/bcmdhd/parameters/firmware_path"
WIFI_DRIVER_FW_PATH_STA     := "/system/etc/firmware/fw_bcmdhd.bin"
WIFI_DRIVER_FW_PATH_AP      := "/system/etc/firmware/fw_bcmdhd_apsta.bin"
WIFI_DRIVER_FW_PATH_P2P     := "/system/etc/firmware/fw_bcmdhd_p2p.bin"

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/alcatel/cocktail/bluetooth
BOARD_BLUEDROID_VENDOR_CONF := device/alcatel/cocktail/bluetooth/vnd_cocktail.txt

